-- Zone ID mappings for DiePlease addon
-- Maps zone names to their UIMap ID
-- Extended version with dungeon IDs
-- Auto-generated by convert_deathlog_to_ripmap.py

ZoneIDs = {
    ["Alterac Mountains"] = 1416,
    ["Arathi Highlands"] = 1417,
    ["Ashenvale"] = 1440,
    ["Azeroth"] = 947,
    ["Azshara"] = 1447,
    ["Badlands"] = 1418,
    ["Blackfathom Deeps"] = 1455,
    ["Blasted Lands"] = 1419,
    ["Burning Steppes"] = 1428,
    ["Darkshore"] = 1439,
    ["Deadwind Pass"] = 1430,
    ["Desolace"] = 1443,
    ["Dun Morogh"] = 1426,
    ["Durotar"] = 1411,
    ["Duskwood"] = 1431,
    ["Dustwallow Marsh"] = 1445,
    ["Eastern Kingdoms"] = 1415,
    ["Eastern Plaguelands"] = 1423,
    ["Elwynn Forest"] = 1429,
    ["Felwood"] = 1448,
    ["Feralas"] = 1444,
    ["Hillsbrad Foothills"] = 1424,
    ["Kalimdor"] = 1414,
    ["Loch Modan"] = 1432,
    ["Molten Core"] = 2717,
    ["Moonglade"] = 1450,
    ["Mulgore"] = 1412,
    ["Ragefire Chasm"] = 1453,
    ["Razorfen Kraul"] = 1458,
    ["Redridge Mountains"] = 1433,
    ["Searing Gorge"] = 1427,
    ["Shadowfang Keep"] = 1457,
    ["Silithus"] = 1451,
    ["Silverpine Forest"] = 1421,
    ["Stonetalon Mountains"] = 1442,
    ["Stranglethorn Vale"] = 1434,
    ["Swamp of Sorrows"] = 1435,
    ["Tanaris"] = 1446,
    ["Teldrassil"] = 1438,
    ["The Barrens"] = 1413,
    ["The Deadmines"] = 1456,
    ["The Hinterlands"] = 1425,
    ["Thousand Needles"] = 1441,
    ["Tirisfal Glades"] = 1420,
    ["Un\'Goro Crater"] = 1449,
    ["Unknown Zone 12"] = 12,
    ["Wailing Caverns"] = 1454,
    ["Western Plaguelands"] = 1422,
    ["Westfall"] = 1436,
    ["Wetlands"] = 1437,
    ["Winterspring"] = 1452,
}

-- Function to get zone ID by name
function GetZoneIDByName(zoneName)
    return ZoneIDs[zoneName]
end
